// Code generated by protoc-gen-go.
// source: crawldoc.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	crawldoc.proto

It has these top-level messages:
	ConnectionInfo
	OutLink
	FetchHint
	CrawlRecord
	CrawlParam
	CrawlHistory
	CrawlDoc
	CrawlDocs
	CrawlRequest
	CrawlResponse
*/
package proto

import proto1 "mustard/internal/github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "mustard/internal/golang.org/x/net/context"
	grpc "mustard/internal/google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type ReturnType int32

const (
	ReturnType_UNKNOWN                 ReturnType = 0
	ReturnType_NODNS                   ReturnType = 1
	ReturnType_NOCONNECTION            ReturnType = 2
	ReturnType_FORBIDDENROBOTS         ReturnType = 3
	ReturnType_TIMEOUT                 ReturnType = 4
	ReturnType_BADTYPE                 ReturnType = 5
	ReturnType_TOOBIG                  ReturnType = 6
	ReturnType_BADHEADER               ReturnType = 7
	ReturnType_NETWORKERROR            ReturnType = 8
	ReturnType_SITEQUEUEFULLFETCHER    ReturnType = 9
	ReturnType_INVALIDURL              ReturnType = 10
	ReturnType_INVALIDREDIRECTURL      ReturnType = 11
	ReturnType_META_REDIRECT           ReturnType = 12
	ReturnType_JS_REDIRECT             ReturnType = 13
	ReturnType_IP_BLACKLISTED          ReturnType = 14
	ReturnType_BADCONTENT              ReturnType = 15
	ReturnType_URL_BLACKLISTED         ReturnType = 16
	ReturnType_SITEQUEUEFULLDISPATCHER ReturnType = 17
	ReturnType_STATUS100               ReturnType = 100
	ReturnType_STATUS101               ReturnType = 101
	ReturnType_STATUS200               ReturnType = 200
	ReturnType_STATUS201               ReturnType = 201
	ReturnType_STATUS202               ReturnType = 202
	ReturnType_STATUS203               ReturnType = 203
	ReturnType_STATUS204               ReturnType = 204
	ReturnType_STATUS205               ReturnType = 205
	ReturnType_STATUS206               ReturnType = 206
	ReturnType_STATUS300               ReturnType = 300
	ReturnType_STATUS301               ReturnType = 301
	ReturnType_STATUS302               ReturnType = 302
	ReturnType_STATUS303               ReturnType = 303
	ReturnType_STATUS304               ReturnType = 304
	ReturnType_STATUS305               ReturnType = 305
	ReturnType_STATUS306               ReturnType = 306
	ReturnType_STATUS307               ReturnType = 307
	ReturnType_STATUS400               ReturnType = 400
	ReturnType_STATUS401               ReturnType = 401
	ReturnType_STATUS402               ReturnType = 402
	ReturnType_STATUS403               ReturnType = 403
	ReturnType_STATUS404               ReturnType = 404
	ReturnType_STATUS405               ReturnType = 405
	ReturnType_STATUS406               ReturnType = 406
	ReturnType_STATUS407               ReturnType = 407
	ReturnType_STATUS408               ReturnType = 408
	ReturnType_STATUS409               ReturnType = 409
	ReturnType_STATUS410               ReturnType = 410
	ReturnType_STATUS411               ReturnType = 411
	ReturnType_STATUS412               ReturnType = 412
	ReturnType_STATUS413               ReturnType = 413
	ReturnType_STATUS414               ReturnType = 414
	ReturnType_STATUS415               ReturnType = 415
	ReturnType_STATUS416               ReturnType = 416
	ReturnType_STATUS417               ReturnType = 417
	ReturnType_STATUS500               ReturnType = 500
	ReturnType_STATUS501               ReturnType = 501
	ReturnType_STATUS502               ReturnType = 502
	ReturnType_STATUS503               ReturnType = 503
	ReturnType_STATUS504               ReturnType = 504
	ReturnType_STATUS505               ReturnType = 505
	ReturnType_STATUS509               ReturnType = 509
	ReturnType_STATUS510               ReturnType = 510
)

var ReturnType_name = map[int32]string{
	0:   "UNKNOWN",
	1:   "NODNS",
	2:   "NOCONNECTION",
	3:   "FORBIDDENROBOTS",
	4:   "TIMEOUT",
	5:   "BADTYPE",
	6:   "TOOBIG",
	7:   "BADHEADER",
	8:   "NETWORKERROR",
	9:   "SITEQUEUEFULLFETCHER",
	10:  "INVALIDURL",
	11:  "INVALIDREDIRECTURL",
	12:  "META_REDIRECT",
	13:  "JS_REDIRECT",
	14:  "IP_BLACKLISTED",
	15:  "BADCONTENT",
	16:  "URL_BLACKLISTED",
	17:  "SITEQUEUEFULLDISPATCHER",
	100: "STATUS100",
	101: "STATUS101",
	200: "STATUS200",
	201: "STATUS201",
	202: "STATUS202",
	203: "STATUS203",
	204: "STATUS204",
	205: "STATUS205",
	206: "STATUS206",
	300: "STATUS300",
	301: "STATUS301",
	302: "STATUS302",
	303: "STATUS303",
	304: "STATUS304",
	305: "STATUS305",
	306: "STATUS306",
	307: "STATUS307",
	400: "STATUS400",
	401: "STATUS401",
	402: "STATUS402",
	403: "STATUS403",
	404: "STATUS404",
	405: "STATUS405",
	406: "STATUS406",
	407: "STATUS407",
	408: "STATUS408",
	409: "STATUS409",
	410: "STATUS410",
	411: "STATUS411",
	412: "STATUS412",
	413: "STATUS413",
	414: "STATUS414",
	415: "STATUS415",
	416: "STATUS416",
	417: "STATUS417",
	500: "STATUS500",
	501: "STATUS501",
	502: "STATUS502",
	503: "STATUS503",
	504: "STATUS504",
	505: "STATUS505",
	509: "STATUS509",
	510: "STATUS510",
}
var ReturnType_value = map[string]int32{
	"UNKNOWN":                 0,
	"NODNS":                   1,
	"NOCONNECTION":            2,
	"FORBIDDENROBOTS":         3,
	"TIMEOUT":                 4,
	"BADTYPE":                 5,
	"TOOBIG":                  6,
	"BADHEADER":               7,
	"NETWORKERROR":            8,
	"SITEQUEUEFULLFETCHER":    9,
	"INVALIDURL":              10,
	"INVALIDREDIRECTURL":      11,
	"META_REDIRECT":           12,
	"JS_REDIRECT":             13,
	"IP_BLACKLISTED":          14,
	"BADCONTENT":              15,
	"URL_BLACKLISTED":         16,
	"SITEQUEUEFULLDISPATCHER": 17,
	"STATUS100":               100,
	"STATUS101":               101,
	"STATUS200":               200,
	"STATUS201":               201,
	"STATUS202":               202,
	"STATUS203":               203,
	"STATUS204":               204,
	"STATUS205":               205,
	"STATUS206":               206,
	"STATUS300":               300,
	"STATUS301":               301,
	"STATUS302":               302,
	"STATUS303":               303,
	"STATUS304":               304,
	"STATUS305":               305,
	"STATUS306":               306,
	"STATUS307":               307,
	"STATUS400":               400,
	"STATUS401":               401,
	"STATUS402":               402,
	"STATUS403":               403,
	"STATUS404":               404,
	"STATUS405":               405,
	"STATUS406":               406,
	"STATUS407":               407,
	"STATUS408":               408,
	"STATUS409":               409,
	"STATUS410":               410,
	"STATUS411":               411,
	"STATUS412":               412,
	"STATUS413":               413,
	"STATUS414":               414,
	"STATUS415":               415,
	"STATUS416":               416,
	"STATUS417":               417,
	"STATUS500":               500,
	"STATUS501":               501,
	"STATUS502":               502,
	"STATUS503":               503,
	"STATUS504":               504,
	"STATUS505":               505,
	"STATUS509":               509,
	"STATUS510":               510,
}

func (x ReturnType) String() string {
	return proto1.EnumName(ReturnType_name, int32(x))
}
func (ReturnType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// tag for source. you can custom
type RequestType int32

const (
	RequestType_TESTING RequestType = 0
	RequestType_GENERAL RequestType = 1
)

var RequestType_name = map[int32]string{
	0: "TESTING",
	1: "GENERAL",
}
var RequestType_value = map[string]int32{
	"TESTING": 0,
	"GENERAL": 1,
}

func (x RequestType) String() string {
	return proto1.EnumName(RequestType_name, int32(x))
}
func (RequestType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Priority int32

const (
	Priority_NORMAL Priority = 0
	Priority_URGENT Priority = 1
)

var Priority_name = map[int32]string{
	0: "NORMAL",
	1: "URGENT",
}
var Priority_value = map[string]int32{
	"NORMAL": 0,
	"URGENT": 1,
}

func (x Priority) String() string {
	return proto1.EnumName(Priority_name, int32(x))
}
func (Priority) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DocType int32

const (
	DocType_NORMALDOC   DocType = 0
	DocType_WEB_MAIN    DocType = 1
	DocType_WEB_HUB     DocType = 2
	DocType_WEB_CONTENT DocType = 3
)

var DocType_name = map[int32]string{
	0: "NORMALDOC",
	1: "WEB_MAIN",
	2: "WEB_HUB",
	3: "WEB_CONTENT",
}
var DocType_value = map[string]int32{
	"NORMALDOC":   0,
	"WEB_MAIN":    1,
	"WEB_HUB":     2,
	"WEB_CONTENT": 3,
}

func (x DocType) String() string {
	return proto1.EnumName(DocType_name, int32(x))
}
func (DocType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type ConnectionInfo struct {
	Host string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Port int32  `protobuf:"varint,2,opt,name=port" json:"port,omitempty"`
}

func (m *ConnectionInfo) Reset()                    { *m = ConnectionInfo{} }
func (m *ConnectionInfo) String() string            { return proto1.CompactTextString(m) }
func (*ConnectionInfo) ProtoMessage()               {}
func (*ConnectionInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type OutLink struct {
	Url  string `protobuf:"bytes,1,opt,name=url" json:"url,omitempty"`
	Text string `protobuf:"bytes,2,opt,name=text" json:"text,omitempty"`
}

func (m *OutLink) Reset()                    { *m = OutLink{} }
func (m *OutLink) String() string            { return proto1.CompactTextString(m) }
func (*OutLink) ProtoMessage()               {}
func (*OutLink) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type FetchHint struct {
	Host     string `protobuf:"bytes,1,opt,name=host" json:"host,omitempty"`
	Path     string `protobuf:"bytes,2,opt,name=path" json:"path,omitempty"`
	Ip       int32  `protobuf:"varint,3,opt,name=ip" json:"ip,omitempty"`
	Port     int32  `protobuf:"varint,4,opt,name=port" json:"port,omitempty"`
	PostData string `protobuf:"bytes,5,opt,name=post_data" json:"post_data,omitempty"`
}

func (m *FetchHint) Reset()                    { *m = FetchHint{} }
func (m *FetchHint) String() string            { return proto1.CompactTextString(m) }
func (*FetchHint) ProtoMessage()               {}
func (*FetchHint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CrawlRecord struct {
	RequestTime int64           `protobuf:"varint,1,opt,name=request_time" json:"request_time,omitempty"`
	Fetcher     *ConnectionInfo `protobuf:"bytes,2,opt,name=fetcher" json:"fetcher,omitempty"`
}

func (m *CrawlRecord) Reset()                    { *m = CrawlRecord{} }
func (m *CrawlRecord) String() string            { return proto1.CompactTextString(m) }
func (*CrawlRecord) ProtoMessage()               {}
func (*CrawlRecord) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *CrawlRecord) GetFetcher() *ConnectionInfo {
	if m != nil {
		return m.Fetcher
	}
	return nil
}

type CrawlParam struct {
	Pri            Priority          `protobuf:"varint,1,opt,name=pri,enum=proto.Priority" json:"pri,omitempty"`
	Hostload       int32             `protobuf:"varint,2,opt,name=hostload" json:"hostload,omitempty"`
	RandomHostload int32             `protobuf:"varint,3,opt,name=random_hostload" json:"random_hostload,omitempty"`
	FetcherCount   int32             `protobuf:"varint,4,opt,name=fetcher_count" json:"fetcher_count,omitempty"`
	DropContent    bool              `protobuf:"varint,5,opt,name=drop_content" json:"drop_content,omitempty"`
	StoreEngine    string            `protobuf:"bytes,7,opt,name=store_engine" json:"store_engine,omitempty"`
	StoreDb        string            `protobuf:"bytes,8,opt,name=store_db" json:"store_db,omitempty"`
	StoreTable     string            `protobuf:"bytes,9,opt,name=store_table" json:"store_table,omitempty"`
	FakeHost       string            `protobuf:"bytes,10,opt,name=fake_host" json:"fake_host,omitempty"`
	Rtype          RequestType       `protobuf:"varint,11,opt,name=rtype,enum=proto.RequestType" json:"rtype,omitempty"`
	FetchHint      *FetchHint        `protobuf:"bytes,12,opt,name=fetch_hint" json:"fetch_hint,omitempty"`
	Receivers      []*ConnectionInfo `protobuf:"bytes,13,rep,name=receivers" json:"receivers,omitempty"`
	PrimaryTag     string            `protobuf:"bytes,14,opt,name=primary_tag" json:"primary_tag,omitempty"`
	SecondaryTag   []string          `protobuf:"bytes,15,rep,name=secondary_tag" json:"secondary_tag,omitempty"`
}

func (m *CrawlParam) Reset()                    { *m = CrawlParam{} }
func (m *CrawlParam) String() string            { return proto1.CompactTextString(m) }
func (*CrawlParam) ProtoMessage()               {}
func (*CrawlParam) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CrawlParam) GetFetchHint() *FetchHint {
	if m != nil {
		return m.FetchHint
	}
	return nil
}

func (m *CrawlParam) GetReceivers() []*ConnectionInfo {
	if m != nil {
		return m.Receivers
	}
	return nil
}

type CrawlHistory struct {
}

func (m *CrawlHistory) Reset()                    { *m = CrawlHistory{} }
func (m *CrawlHistory) String() string            { return proto1.CompactTextString(m) }
func (*CrawlHistory) ProtoMessage()               {}
func (*CrawlHistory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type CrawlDoc struct {
	Docid      string `protobuf:"bytes,1,opt,name=docid" json:"docid,omitempty"`
	RequestUrl string `protobuf:"bytes,2,opt,name=request_url" json:"request_url,omitempty"`
	// url use to crawl. it's generated base on request url
	Url               string     `protobuf:"bytes,3,opt,name=url" json:"url,omitempty"`
	RedirectUrl       string     `protobuf:"bytes,4,opt,name=redirect_url" json:"redirect_url,omitempty"`
	Code              ReturnType `protobuf:"varint,5,opt,name=code,enum=proto.ReturnType" json:"code,omitempty"`
	Content           string     `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
	ContentCompressed bool       `protobuf:"varint,7,opt,name=content_compressed" json:"content_compressed,omitempty"`
	// time the doc fetched
	Timestamp         int64      `protobuf:"varint,8,opt,name=timestamp" json:"timestamp,omitempty"`
	IndomainOutlinks  []*OutLink `protobuf:"bytes,9,rep,name=indomain_outlinks" json:"indomain_outlinks,omitempty"`
	OutdomainOutlinks []*OutLink `protobuf:"bytes,10,rep,name=outdomain_outlinks" json:"outdomain_outlinks,omitempty"`
	// content hash(128 bit)
	Chash_0 int64 `protobuf:"varint,11,opt,name=chash_0" json:"chash_0,omitempty"`
	Chash_1 int64 `protobuf:"varint,12,opt,name=chash_1" json:"chash_1,omitempty"`
	// original encoding which is deteched by the page content
	OrigEncoding int32 `protobuf:"varint,13,opt,name=orig_encoding" json:"orig_encoding,omitempty"`
	// encoding after convert to utf8
	// the same with orig_encoding if convert fail
	// utf8 if convert success
	ConvEncoding int32 `protobuf:"varint,14,opt,name=conv_encoding" json:"conv_encoding,omitempty"`
	// language the page is detected to
	Language int32 `protobuf:"varint,15,opt,name=language" json:"language,omitempty"`
	// content type of the page, eg text/html
	ContentType string       `protobuf:"bytes,16,opt,name=content_type" json:"content_type,omitempty"`
	Header      string       `protobuf:"bytes,18,opt,name=header" json:"header,omitempty"`
	TimeUsed    int64        `protobuf:"varint,19,opt,name=time_used" json:"time_used,omitempty"`
	Reservation string       `protobuf:"bytes,20,opt,name=reservation" json:"reservation,omitempty"`
	Dtype       DocType      `protobuf:"varint,21,opt,name=dtype,enum=proto.DocType" json:"dtype,omitempty"`
	CrawlParam  *CrawlParam  `protobuf:"bytes,50,opt,name=crawl_param" json:"crawl_param,omitempty"`
	CrawlRecord *CrawlRecord `protobuf:"bytes,60,opt,name=crawl_record" json:"crawl_record,omitempty"`
}

func (m *CrawlDoc) Reset()                    { *m = CrawlDoc{} }
func (m *CrawlDoc) String() string            { return proto1.CompactTextString(m) }
func (*CrawlDoc) ProtoMessage()               {}
func (*CrawlDoc) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *CrawlDoc) GetIndomainOutlinks() []*OutLink {
	if m != nil {
		return m.IndomainOutlinks
	}
	return nil
}

func (m *CrawlDoc) GetOutdomainOutlinks() []*OutLink {
	if m != nil {
		return m.OutdomainOutlinks
	}
	return nil
}

func (m *CrawlDoc) GetCrawlParam() *CrawlParam {
	if m != nil {
		return m.CrawlParam
	}
	return nil
}

func (m *CrawlDoc) GetCrawlRecord() *CrawlRecord {
	if m != nil {
		return m.CrawlRecord
	}
	return nil
}

type CrawlDocs struct {
	Docs []*CrawlDoc `protobuf:"bytes,1,rep,name=docs" json:"docs,omitempty"`
}

func (m *CrawlDocs) Reset()                    { *m = CrawlDocs{} }
func (m *CrawlDocs) String() string            { return proto1.CompactTextString(m) }
func (*CrawlDocs) ProtoMessage()               {}
func (*CrawlDocs) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CrawlDocs) GetDocs() []*CrawlDoc {
	if m != nil {
		return m.Docs
	}
	return nil
}

type CrawlRequest struct {
	Request string `protobuf:"bytes,1,opt,name=request" json:"request,omitempty"`
}

func (m *CrawlRequest) Reset()                    { *m = CrawlRequest{} }
func (m *CrawlRequest) String() string            { return proto1.CompactTextString(m) }
func (*CrawlRequest) ProtoMessage()               {}
func (*CrawlRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type CrawlResponse struct {
	Ok  bool  `protobuf:"varint,1,opt,name=ok" json:"ok,omitempty"`
	Ret int64 `protobuf:"varint,2,opt,name=ret" json:"ret,omitempty"`
}

func (m *CrawlResponse) Reset()                    { *m = CrawlResponse{} }
func (m *CrawlResponse) String() string            { return proto1.CompactTextString(m) }
func (*CrawlResponse) ProtoMessage()               {}
func (*CrawlResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto1.RegisterType((*ConnectionInfo)(nil), "proto.ConnectionInfo")
	proto1.RegisterType((*OutLink)(nil), "proto.OutLink")
	proto1.RegisterType((*FetchHint)(nil), "proto.FetchHint")
	proto1.RegisterType((*CrawlRecord)(nil), "proto.CrawlRecord")
	proto1.RegisterType((*CrawlParam)(nil), "proto.CrawlParam")
	proto1.RegisterType((*CrawlHistory)(nil), "proto.CrawlHistory")
	proto1.RegisterType((*CrawlDoc)(nil), "proto.CrawlDoc")
	proto1.RegisterType((*CrawlDocs)(nil), "proto.CrawlDocs")
	proto1.RegisterType((*CrawlRequest)(nil), "proto.CrawlRequest")
	proto1.RegisterType((*CrawlResponse)(nil), "proto.CrawlResponse")
	proto1.RegisterEnum("proto.ReturnType", ReturnType_name, ReturnType_value)
	proto1.RegisterEnum("proto.RequestType", RequestType_name, RequestType_value)
	proto1.RegisterEnum("proto.Priority", Priority_name, Priority_value)
	proto1.RegisterEnum("proto.DocType", DocType_name, DocType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// Client API for CrawlService service

type CrawlServiceClient interface {
	Feed(ctx context.Context, in *CrawlDocs, opts ...grpc.CallOption) (*CrawlResponse, error)
	IsHealthy(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error)
}

type crawlServiceClient struct {
	cc *grpc.ClientConn
}

func NewCrawlServiceClient(cc *grpc.ClientConn) CrawlServiceClient {
	return &crawlServiceClient{cc}
}

func (c *crawlServiceClient) Feed(ctx context.Context, in *CrawlDocs, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := grpc.Invoke(ctx, "/proto.CrawlService/Feed", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *crawlServiceClient) IsHealthy(ctx context.Context, in *CrawlRequest, opts ...grpc.CallOption) (*CrawlResponse, error) {
	out := new(CrawlResponse)
	err := grpc.Invoke(ctx, "/proto.CrawlService/IsHealthy", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for CrawlService service

type CrawlServiceServer interface {
	Feed(context.Context, *CrawlDocs) (*CrawlResponse, error)
	IsHealthy(context.Context, *CrawlRequest) (*CrawlResponse, error)
}

func RegisterCrawlServiceServer(s *grpc.Server, srv CrawlServiceServer) {
	s.RegisterService(&_CrawlService_serviceDesc, srv)
}

func _CrawlService_Feed_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CrawlDocs)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CrawlServiceServer).Feed(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _CrawlService_IsHealthy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(CrawlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(CrawlServiceServer).IsHealthy(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

var _CrawlService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.CrawlService",
	HandlerType: (*CrawlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Feed",
			Handler:    _CrawlService_Feed_Handler,
		},
		{
			MethodName: "IsHealthy",
			Handler:    _CrawlService_IsHealthy_Handler,
		},
	},
	Streams: []grpc.StreamDesc{},
}

var fileDescriptor0 = []byte{
	// 1512 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x74, 0x56, 0x5b, 0x6f, 0xdb, 0x46,
	0x16, 0x8e, 0x2d, 0xd9, 0x92, 0x46, 0xb2, 0x3c, 0x9e, 0x38, 0x1b, 0x6e, 0x76, 0x81, 0xcd, 0x6a,
	0xb7, 0x48, 0x60, 0xa0, 0xa9, 0x25, 0xd9, 0x4e, 0x82, 0xb6, 0x0f, 0xb2, 0x44, 0xdb, 0x6c, 0x64,
	0xd2, 0x1d, 0x51, 0x0d, 0xfa, 0x24, 0xd0, 0x12, 0x6d, 0x11, 0xb1, 0x49, 0x95, 0xa4, 0xd2, 0xba,
	0x3f, 0xa2, 0xe8, 0xfd, 0x7e, 0x45, 0x5f, 0x7b, 0xef, 0x9f, 0xe8, 0xfd, 0xd7, 0xf4, 0x0a, 0xb4,
	0x45, 0xcf, 0x19, 0x0e, 0x25, 0x4d, 0xd0, 0x3c, 0x79, 0xbe, 0xef, 0x9c, 0xc3, 0x99, 0x73, 0xf9,
	0x8e, 0x4c, 0xca, 0xfd, 0xd0, 0x79, 0xfa, 0x64, 0x10, 0xf4, 0xaf, 0x8d, 0xc2, 0x20, 0x0e, 0xd8,
	0x82, 0xf8, 0x53, 0xb9, 0x41, 0xca, 0xcd, 0xc0, 0xf7, 0xdd, 0x7e, 0xec, 0x05, 0xbe, 0xe1, 0x1f,
	0x05, 0x8c, 0x91, 0xec, 0x30, 0x88, 0x62, 0x6d, 0xee, 0xf2, 0xdc, 0xd5, 0x02, 0x17, 0x67, 0xe4,
	0x46, 0x41, 0x18, 0x6b, 0xf3, 0xc0, 0x2d, 0x70, 0x71, 0xae, 0x3c, 0x44, 0x72, 0xd6, 0x38, 0x6e,
	0x7b, 0xfe, 0x1d, 0x46, 0x49, 0x66, 0x1c, 0x9e, 0xc8, 0x08, 0x3c, 0x62, 0x40, 0xec, 0x3e, 0x93,
	0x04, 0xc0, 0x47, 0xf0, 0x5c, 0x89, 0x49, 0x61, 0xc7, 0x8d, 0xfb, 0xc3, 0x3d, 0xcf, 0x8f, 0xef,
	0x7b, 0x8b, 0x13, 0x0f, 0xd3, 0x20, 0x3c, 0xb3, 0x32, 0x99, 0xf7, 0x46, 0x5a, 0x46, 0xdc, 0x0b,
	0xa7, 0xc9, 0x4b, 0xb2, 0xd3, 0x97, 0xb0, 0x7f, 0x91, 0xc2, 0x08, 0xe2, 0x7b, 0x03, 0x27, 0x76,
	0xb4, 0x05, 0x11, 0x9c, 0x47, 0xa2, 0x05, 0xb8, 0xe2, 0x90, 0x62, 0x13, 0x33, 0xe7, 0x6e, 0x3f,
	0x08, 0x07, 0xec, 0xbf, 0xa4, 0x14, 0xba, 0x4f, 0x8d, 0x5d, 0x70, 0x8f, 0xbd, 0x53, 0x57, 0xdc,
	0x9f, 0xe1, 0x45, 0xc9, 0xd9, 0x40, 0x31, 0x48, 0xec, 0x08, 0xdf, 0xe9, 0x86, 0xe2, 0x25, 0xc5,
	0xda, 0x85, 0xa4, 0x64, 0xd7, 0xd4, 0x42, 0xf1, 0xd4, 0xab, 0xf2, 0x5c, 0x96, 0x10, 0x71, 0xc7,
	0x81, 0x13, 0x3a, 0xa7, 0x70, 0x45, 0x66, 0x14, 0x7a, 0xe2, 0xcb, 0xe5, 0xda, 0xb2, 0x8c, 0x3d,
	0x08, 0xbd, 0x20, 0xf4, 0xe2, 0x33, 0x8e, 0x36, 0x76, 0x89, 0xe4, 0x31, 0xe3, 0x93, 0xc0, 0x19,
	0xc8, 0x9a, 0x4e, 0x30, 0xbb, 0x42, 0x96, 0x43, 0xc7, 0x1f, 0x04, 0xa7, 0xbd, 0x89, 0x4b, 0x92,
	0x7e, 0x39, 0xa1, 0xf7, 0x52, 0xc7, 0xff, 0x91, 0x25, 0xf9, 0x82, 0x5e, 0x3f, 0x18, 0xfb, 0x69,
	0x4d, 0x4a, 0x92, 0x6c, 0x22, 0x87, 0xf9, 0x0e, 0xc2, 0x60, 0x04, 0x1e, 0x7e, 0xec, 0x82, 0x0f,
	0x96, 0x27, 0xcf, 0x8b, 0xc8, 0x35, 0x13, 0x0a, 0x5d, 0xa2, 0x38, 0x08, 0xdd, 0x9e, 0xeb, 0x1f,
	0x7b, 0xbe, 0xab, 0xe5, 0x44, 0x05, 0x8b, 0x82, 0xd3, 0x05, 0xc5, 0xfe, 0x49, 0xf2, 0x89, 0xcb,
	0xe0, 0x50, 0xcb, 0x0b, 0x73, 0x4e, 0xe0, 0xd6, 0x21, 0xfb, 0x0f, 0x49, 0x3c, 0x7b, 0xb1, 0x73,
	0x78, 0xe2, 0x6a, 0x05, 0x61, 0x25, 0x82, 0xb2, 0x91, 0xc1, 0xee, 0x1c, 0x39, 0x77, 0x5c, 0x91,
	0x8d, 0x46, 0x92, 0xee, 0x20, 0x81, 0x79, 0xb0, 0xab, 0x64, 0x21, 0x8c, 0xcf, 0x46, 0xae, 0x56,
	0x14, 0xd5, 0x62, 0xb2, 0x5a, 0x5c, 0xb6, 0x03, 0x2c, 0x3c, 0x71, 0x80, 0xae, 0x10, 0x91, 0x58,
	0x6f, 0x08, 0xe3, 0xa3, 0x95, 0x44, 0x63, 0xa8, 0x74, 0x9f, 0x8c, 0x15, 0x2f, 0x1c, 0x4d, 0x26,
	0xac, 0x4e, 0x0a, 0xa1, 0xdb, 0x77, 0xbd, 0xbb, 0x6e, 0x18, 0x69, 0x4b, 0x97, 0x33, 0xf7, 0x6f,
	0xe4, 0xd4, 0x0f, 0xb3, 0x81, 0xfe, 0x9c, 0x3a, 0xe1, 0x19, 0xe4, 0x73, 0xac, 0x95, 0x93, 0x6c,
	0x24, 0x65, 0x3b, 0xc7, 0x58, 0xf4, 0x08, 0x26, 0xc9, 0x1f, 0xa4, 0x2e, 0xcb, 0xf0, 0xe5, 0x02,
	0x2f, 0x4d, 0x48, 0x70, 0xaa, 0x94, 0x49, 0x49, 0xcc, 0xc3, 0x9e, 0x87, 0x75, 0x38, 0xab, 0x7c,
	0xb8, 0x48, 0xf2, 0x82, 0x68, 0x05, 0x7d, 0xb6, 0x4a, 0x16, 0x40, 0x85, 0xde, 0x40, 0x8e, 0x7e,
	0x02, 0xf0, 0xe2, 0x74, 0x2e, 0x51, 0x4a, 0x89, 0x04, 0x88, 0xa4, 0xba, 0xa0, 0x28, 0xa9, 0xb1,
	0xcc, 0x54, 0x63, 0x62, 0x94, 0x07, 0x1e, 0x3c, 0x3e, 0x89, 0xc9, 0x26, 0x7d, 0x4b, 0x39, 0x0c,
	0x7a, 0x80, 0x64, 0xfb, 0xc1, 0xc0, 0x15, 0x5d, 0x2f, 0xd7, 0x56, 0x26, 0xd5, 0x8d, 0xc7, 0xa1,
	0x2f, 0x8a, 0x2b, 0xcc, 0x4c, 0x23, 0xb9, 0x74, 0x3e, 0x16, 0x93, 0xee, 0x4a, 0xc8, 0x1e, 0x24,
	0x4c, 0x1e, 0x61, 0x82, 0x4e, 0x47, 0xa1, 0x1b, 0x45, 0xee, 0x40, 0x4c, 0x48, 0x9e, 0xaf, 0x48,
	0x4b, 0x73, 0x62, 0x60, 0xff, 0x26, 0x05, 0x54, 0x55, 0x14, 0x3b, 0xa7, 0x23, 0x31, 0x28, 0x19,
	0x3e, 0x25, 0xd8, 0xc3, 0x64, 0xc5, 0xc3, 0x09, 0x76, 0x3c, 0xbf, 0x17, 0x8c, 0xe3, 0x13, 0x58,
	0x1d, 0x11, 0x0c, 0x0c, 0x76, 0xa6, 0x2c, 0x9f, 0x26, 0x37, 0x0a, 0xa7, 0xa9, 0xa3, 0x25, 0xfd,
	0xd8, 0xa3, 0x84, 0x41, 0xcc, 0xbd, 0xd1, 0xe4, 0x6f, 0xa3, 0x57, 0x26, 0x9e, 0x93, 0xf0, 0x8b,
	0x90, 0xe2, 0xd0, 0x89, 0x86, 0xbd, 0x75, 0x31, 0x6a, 0x19, 0xbe, 0x28, 0xe0, 0xfa, 0xd4, 0x50,
	0x15, 0x43, 0x95, 0x1a, 0xaa, 0xd8, 0x69, 0x50, 0xec, 0x31, 0xa8, 0x02, 0x6a, 0xe4, 0xf9, 0xc7,
	0x30, 0x43, 0x42, 0x5e, 0x48, 0xea, 0x92, 0x43, 0x27, 0xa8, 0xc2, 0xdd, 0xa9, 0x53, 0x39, 0x71,
	0x42, 0x72, 0xe2, 0x04, 0x6a, 0x3f, 0x71, 0xfc, 0xe3, 0xb1, 0x73, 0xec, 0xc2, 0xb8, 0x08, 0xb5,
	0xa7, 0x18, 0x9b, 0x98, 0x16, 0x58, 0xe8, 0x80, 0x26, 0x4d, 0x94, 0x1c, 0xf6, 0x88, 0xfd, 0x83,
	0x2c, 0x0e, 0x5d, 0x67, 0x00, 0xeb, 0x88, 0x09, 0xa3, 0x44, 0x28, 0x2c, 0xac, 0x6d, 0x6f, 0x8c,
	0x2d, 0x39, 0x2f, 0xde, 0x9e, 0x47, 0xa2, 0x8b, 0x9d, 0xb8, 0x8c, 0xf3, 0x14, 0xb9, 0xe1, 0x5d,
	0x07, 0xc7, 0x5c, 0x5b, 0x4d, 0x67, 0x63, 0x42, 0xb1, 0xff, 0xc3, 0x1c, 0x8a, 0x2b, 0x2f, 0x88,
	0xe1, 0x48, 0x6b, 0x08, 0x23, 0x9a, 0xc8, 0x4e, 0x18, 0x59, 0x8d, 0x14, 0xc5, 0x0f, 0x47, 0x6f,
	0x84, 0xbb, 0x4d, 0xab, 0x09, 0xdd, 0xa5, 0x83, 0x34, 0x5d, 0x7a, 0x9c, 0xf4, 0xa7, 0x0b, 0x70,
	0x13, 0x72, 0x12, 0x31, 0xa1, 0xd8, 0xb9, 0xda, 0x23, 0x22, 0x88, 0xcd, 0x06, 0x25, 0xdb, 0x98,
	0x27, 0xdf, 0x4e, 0x40, 0x65, 0x9d, 0x14, 0x52, 0x91, 0x44, 0x50, 0xd8, 0x2c, 0x08, 0x23, 0x02,
	0x91, 0x60, 0x83, 0x97, 0x67, 0x63, 0xc1, 0xce, 0x85, 0xb1, 0x72, 0x55, 0xea, 0x4c, 0xae, 0x0b,
	0x9c, 0x63, 0xa9, 0x18, 0x29, 0xae, 0x14, 0x56, 0xaa, 0x64, 0x49, 0x7a, 0x46, 0xa3, 0xc0, 0x8f,
	0x5c, 0xfc, 0x5d, 0x09, 0xee, 0x08, 0xaf, 0x3c, 0x87, 0x13, 0xca, 0x2b, 0x74, 0x93, 0xdf, 0xab,
	0x0c, 0xc7, 0xe3, 0xda, 0xef, 0x39, 0x42, 0xa6, 0x4a, 0x61, 0x45, 0x92, 0xeb, 0x9a, 0xb7, 0x4c,
	0xeb, 0xb6, 0x49, 0xcf, 0xb1, 0x02, 0x59, 0x30, 0xad, 0x96, 0xd9, 0xa1, 0x73, 0x10, 0x58, 0x32,
	0xad, 0xa6, 0x65, 0x9a, 0x7a, 0xd3, 0x36, 0x2c, 0x93, 0xce, 0xb3, 0xf3, 0x64, 0x79, 0xc7, 0xe2,
	0xdb, 0x46, 0xab, 0xa5, 0x9b, 0xdc, 0xda, 0xb6, 0xec, 0x0e, 0xcd, 0x60, 0xb8, 0x6d, 0xec, 0xeb,
	0x56, 0xd7, 0xa6, 0x59, 0x04, 0xdb, 0x8d, 0x96, 0xfd, 0xe4, 0x81, 0x4e, 0x17, 0x18, 0x21, 0x8b,
	0xb6, 0x65, 0x6d, 0x1b, 0xbb, 0x74, 0x91, 0x2d, 0x91, 0x02, 0x18, 0xf6, 0xf4, 0x46, 0x4b, 0xe7,
	0x34, 0x27, 0xbe, 0xad, 0xdb, 0xb7, 0x2d, 0x7e, 0x4b, 0xe7, 0xdc, 0xe2, 0x34, 0x0f, 0x19, 0xae,
	0x76, 0x0c, 0x5b, 0x7f, 0xbc, 0xab, 0x77, 0xf5, 0x9d, 0x6e, 0xbb, 0xbd, 0xa3, 0xdb, 0xcd, 0x3d,
	0xf0, 0x2d, 0x40, 0x42, 0xc4, 0x30, 0x9f, 0x68, 0xb4, 0x8d, 0x56, 0x97, 0xb7, 0x29, 0x81, 0xa9,
	0x61, 0x12, 0x73, 0xbd, 0x65, 0x70, 0x78, 0x1d, 0xf2, 0x45, 0xb6, 0x42, 0x96, 0xf6, 0x75, 0xbb,
	0xd1, 0x4b, 0x59, 0x5a, 0x62, 0xcb, 0xa4, 0xf8, 0x58, 0x67, 0x4a, 0x2c, 0xc1, 0x8f, 0x6c, 0xd9,
	0x38, 0xe8, 0x6d, 0xb7, 0x1b, 0xcd, 0x5b, 0x6d, 0xa3, 0x63, 0xeb, 0x2d, 0x5a, 0xc6, 0xef, 0xc3,
	0xd3, 0x20, 0x51, 0x5b, 0x37, 0x6d, 0xba, 0x8c, 0x59, 0xc2, 0x07, 0x15, 0x27, 0x0a, 0x23, 0x79,
	0x51, 0x79, 0x5e, 0xcb, 0xe8, 0x1c, 0x34, 0x92, 0x17, 0xae, 0x60, 0x72, 0x1d, 0xbb, 0x61, 0x77,
	0x3b, 0xd5, 0xf5, 0x75, 0x3a, 0x98, 0x85, 0x55, 0x8a, 0x0d, 0x91, 0xb0, 0x06, 0xd6, 0xaf, 0xe6,
	0x66, 0x71, 0x95, 0x7e, 0xad, 0xe0, 0x1a, 0xfd, 0x46, 0xc1, 0x75, 0xfa, 0xad, 0x82, 0x37, 0xe8,
	0x77, 0x0a, 0xde, 0xa4, 0xdf, 0x2b, 0x78, 0x8b, 0xfe, 0x30, 0x83, 0xeb, 0x70, 0xdf, 0x47, 0xf3,
	0xb3, 0xb8, 0x4a, 0x3f, 0x56, 0x70, 0x8d, 0x7e, 0xa2, 0xe0, 0x3a, 0xfd, 0x54, 0xc1, 0x1b, 0xf4,
	0x33, 0x05, 0x6f, 0xd2, 0xcf, 0x15, 0xbc, 0x45, 0xbf, 0x50, 0xf0, 0x75, 0xfa, 0xe5, 0x0c, 0xde,
	0x80, 0xfb, 0x9f, 0xcf, 0xcc, 0xe2, 0x2a, 0x7d, 0x41, 0xc1, 0x35, 0xfa, 0xa2, 0x82, 0xeb, 0xf4,
	0x25, 0x05, 0x6f, 0xd0, 0x97, 0x15, 0xbc, 0x49, 0x5f, 0x51, 0xf0, 0x16, 0x7d, 0x55, 0xc1, 0xd7,
	0xe9, 0x6b, 0x0a, 0xbe, 0x41, 0x5f, 0x57, 0xf0, 0x4d, 0xfa, 0xc6, 0x2c, 0xae, 0xae, 0xd3, 0x37,
	0x15, 0x5c, 0xa5, 0x6f, 0x29, 0xb8, 0x46, 0xdf, 0x56, 0x70, 0x9d, 0xbe, 0xa3, 0xe0, 0x0d, 0xfa,
	0xae, 0x82, 0x37, 0xe9, 0x7b, 0x0a, 0xde, 0xa2, 0xef, 0x2b, 0xf8, 0x3a, 0xfd, 0x60, 0x06, 0x6f,
	0x42, 0x7d, 0x7e, 0x54, 0x70, 0x95, 0xfe, 0xa4, 0xe0, 0x1a, 0xfd, 0x59, 0xc1, 0x75, 0xfa, 0x8b,
	0x82, 0x37, 0xe8, 0xaf, 0x0a, 0xde, 0xa4, 0xbf, 0x29, 0xf8, 0x26, 0xfd, 0x63, 0x16, 0x43, 0xbe,
	0x7f, 0x66, 0xd6, 0xae, 0x90, 0xe2, 0xcc, 0x7f, 0x21, 0x42, 0xbf, 0x7a, 0xc7, 0x36, 0xcc, 0x5d,
	0x90, 0x3f, 0x80, 0x5d, 0xdd, 0xd4, 0x79, 0xa3, 0x4d, 0xe7, 0xd6, 0x2a, 0x24, 0x9f, 0xfe, 0x73,
	0x87, 0x5a, 0x36, 0x2d, 0xbe, 0x0f, 0xfc, 0x39, 0x3c, 0x77, 0xf9, 0x2e, 0x8a, 0x65, 0x6e, 0xad,
	0x45, 0x72, 0x72, 0xaf, 0xe2, 0xd8, 0x27, 0x2e, 0x2d, 0xab, 0x09, 0x5e, 0x25, 0x92, 0xbf, 0xad,
	0x6f, 0xf7, 0xf6, 0x1b, 0x86, 0x09, 0xcb, 0x04, 0x3e, 0x8c, 0x68, 0xaf, 0xbb, 0x0d, 0x7b, 0x04,
	0x64, 0x89, 0x20, 0x95, 0x5c, 0xa6, 0xf6, 0xac, 0x5c, 0x77, 0x1d, 0xd8, 0xe1, 0x5e, 0xdf, 0x65,
	0xeb, 0x24, 0xbb, 0xe3, 0xc2, 0xae, 0xa7, 0xf7, 0x6c, 0xc7, 0xe8, 0xd2, 0xaa, 0xba, 0x6b, 0x93,
	0x9d, 0x57, 0x39, 0xc7, 0x6e, 0x90, 0x82, 0x11, 0xed, 0xb9, 0xce, 0x49, 0x3c, 0x3c, 0x63, 0xe7,
	0x55, 0x27, 0x91, 0xeb, 0xfd, 0x22, 0x0f, 0x17, 0x05, 0x5d, 0xff, 0x2b, 0x00, 0x00, 0xff, 0xff,
	0x3d, 0xa1, 0x1a, 0x6a, 0x47, 0x0c, 0x00, 0x00,
}
