// Code generated by protoc-gen-go.
// source: example.proto
// DO NOT EDIT!

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	example.proto

It has these top-level messages:
	Person
	GreetRequest
	GreetResponse
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto1.ProtoPackageIsVersion1

type Person struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age" json:"age,omitempty"`
}

func (m *Person) Reset()                    { *m = Person{} }
func (m *Person) String() string            { return proto1.CompactTextString(m) }
func (*Person) ProtoMessage()               {}
func (*Person) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GreetRequest struct {
	Person  *Person          `protobuf:"bytes,1,opt,name=person" json:"person,omitempty"`
	Hobbies []string         `protobuf:"bytes,2,rep,name=hobbies" json:"hobbies,omitempty"`
	Keyword map[string]int32 `protobuf:"bytes,3,rep,name=keyword" json:"keyword,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
}

func (m *GreetRequest) Reset()                    { *m = GreetRequest{} }
func (m *GreetRequest) String() string            { return proto1.CompactTextString(m) }
func (*GreetRequest) ProtoMessage()               {}
func (*GreetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GreetRequest) GetPerson() *Person {
	if m != nil {
		return m.Person
	}
	return nil
}

func (m *GreetRequest) GetKeyword() map[string]int32 {
	if m != nil {
		return m.Keyword
	}
	return nil
}

type GreetResponse struct {
	Content     string `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Attatchment string `protobuf:"bytes,2,opt,name=attatchment" json:"attatchment,omitempty"`
}

func (m *GreetResponse) Reset()                    { *m = GreetResponse{} }
func (m *GreetResponse) String() string            { return proto1.CompactTextString(m) }
func (*GreetResponse) ProtoMessage()               {}
func (*GreetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func init() {
	proto1.RegisterType((*Person)(nil), "proto.Person")
	proto1.RegisterType((*GreetRequest)(nil), "proto.GreetRequest")
	proto1.RegisterType((*GreetResponse)(nil), "proto.GreetResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion1

// Client API for GreetingService service

type GreetingServiceClient interface {
	Greeting(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	GreetOnce(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error)
	GreetMulti(ctx context.Context, opts ...grpc.CallOption) (GreetingService_GreetMultiClient, error)
}

type greetingServiceClient struct {
	cc *grpc.ClientConn
}

func NewGreetingServiceClient(cc *grpc.ClientConn) GreetingServiceClient {
	return &greetingServiceClient{cc}
}

func (c *greetingServiceClient) Greeting(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := grpc.Invoke(ctx, "/proto.GreetingService/Greeting", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) GreetOnce(ctx context.Context, in *GreetRequest, opts ...grpc.CallOption) (*GreetResponse, error) {
	out := new(GreetResponse)
	err := grpc.Invoke(ctx, "/proto.GreetingService/GreetOnce", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greetingServiceClient) GreetMulti(ctx context.Context, opts ...grpc.CallOption) (GreetingService_GreetMultiClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GreetingService_serviceDesc.Streams[0], c.cc, "/proto.GreetingService/GreetMulti", opts...)
	if err != nil {
		return nil, err
	}
	x := &greetingServiceGreetMultiClient{stream}
	return x, nil
}

type GreetingService_GreetMultiClient interface {
	Send(*GreetRequest) error
	Recv() (*GreetResponse, error)
	grpc.ClientStream
}

type greetingServiceGreetMultiClient struct {
	grpc.ClientStream
}

func (x *greetingServiceGreetMultiClient) Send(m *GreetRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *greetingServiceGreetMultiClient) Recv() (*GreetResponse, error) {
	m := new(GreetResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GreetingService service

type GreetingServiceServer interface {
	Greeting(context.Context, *GreetRequest) (*GreetResponse, error)
	GreetOnce(context.Context, *GreetRequest) (*GreetResponse, error)
	GreetMulti(GreetingService_GreetMultiServer) error
}

func RegisterGreetingServiceServer(s *grpc.Server, srv GreetingServiceServer) {
	s.RegisterService(&_GreetingService_serviceDesc, srv)
}

func _GreetingService_Greeting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GreetingServiceServer).Greeting(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GreetingService_GreetOnce_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error) (interface{}, error) {
	in := new(GreetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	out, err := srv.(GreetingServiceServer).GreetOnce(ctx, in)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func _GreetingService_GreetMulti_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GreetingServiceServer).GreetMulti(&greetingServiceGreetMultiServer{stream})
}

type GreetingService_GreetMultiServer interface {
	Send(*GreetResponse) error
	Recv() (*GreetRequest, error)
	grpc.ServerStream
}

type greetingServiceGreetMultiServer struct {
	grpc.ServerStream
}

func (x *greetingServiceGreetMultiServer) Send(m *GreetResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *greetingServiceGreetMultiServer) Recv() (*GreetRequest, error) {
	m := new(GreetRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GreetingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.GreetingService",
	HandlerType: (*GreetingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Greeting",
			Handler:    _GreetingService_Greeting_Handler,
		},
		{
			MethodName: "GreetOnce",
			Handler:    _GreetingService_GreetOnce_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GreetMulti",
			Handler:       _GreetingService_GreetMulti_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 283 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x94, 0x8e, 0xd1, 0x4a, 0xc3, 0x30,
	0x14, 0x86, 0xcd, 0x6a, 0x3b, 0x7b, 0xda, 0x32, 0xc8, 0xbc, 0x28, 0x03, 0x61, 0xd4, 0x9b, 0x5d,
	0x15, 0xad, 0x88, 0x43, 0xf0, 0x52, 0xbc, 0x10, 0x51, 0xf4, 0x09, 0xd2, 0x7a, 0xd8, 0x8a, 0x6d,
	0x52, 0xd3, 0x74, 0xba, 0xc7, 0xf1, 0x59, 0x7c, 0x31, 0xd3, 0x34, 0xc2, 0x04, 0x6f, 0x76, 0x15,
	0xce, 0x9f, 0xf3, 0x7d, 0xe7, 0x87, 0x08, 0x3f, 0x59, 0xdd, 0x54, 0x98, 0x36, 0x52, 0x28, 0x41,
	0x5d, 0xf3, 0x24, 0xa7, 0xe0, 0x3d, 0xa1, 0x6c, 0x05, 0xa7, 0x21, 0x1c, 0x72, 0x56, 0x63, 0x4c,
	0xe6, 0x64, 0xe1, 0xd3, 0x00, 0x1c, 0xb6, 0xc2, 0x78, 0xa4, 0x07, 0x37, 0xf9, 0x22, 0x10, 0xde,
	0x49, 0x44, 0xf5, 0x8c, 0xef, 0x1d, 0xb6, 0x8a, 0x9e, 0x80, 0xd7, 0x18, 0xca, 0x6c, 0x07, 0x59,
	0x34, 0x48, 0x53, 0xab, 0x9a, 0xc0, 0x78, 0x2d, 0xf2, 0xbc, 0xc4, 0x56, 0x0b, 0x1c, 0x6d, 0x3b,
	0x87, 0xf1, 0x1b, 0x6e, 0x3f, 0x84, 0x7c, 0x8d, 0x1d, 0x1d, 0x04, 0xd9, 0xdc, 0x02, 0xbb, 0xd6,
	0xf4, 0x7e, 0x58, 0xb9, 0xe5, 0x4a, 0x6e, 0x67, 0x29, 0x84, 0xbb, 0x73, 0x5f, 0x48, 0x2b, 0x6c,
	0xbb, 0x08, 0xdc, 0x0d, 0xab, 0x3a, 0xdb, 0xef, 0x7a, 0xb4, 0x24, 0xc9, 0x25, 0x44, 0x56, 0xd6,
	0x36, 0x82, 0xb7, 0xd8, 0x97, 0x28, 0x04, 0x57, 0xc8, 0x95, 0x85, 0xa6, 0x10, 0x30, 0xa5, 0x98,
	0x2a, 0xd6, 0x75, 0x1f, 0xf6, 0xa8, 0x9f, 0x7d, 0x13, 0x98, 0x18, 0xae, 0xe4, 0xab, 0x17, 0x94,
	0x9b, 0xb2, 0x40, 0x7a, 0x05, 0x47, 0xbf, 0x11, 0x9d, 0xfe, 0x53, 0x74, 0x76, 0xfc, 0x37, 0x1c,
	0x0e, 0x26, 0x07, 0x74, 0x09, 0xbe, 0x89, 0x1e, 0xb9, 0xb6, 0xec, 0x45, 0xde, 0x00, 0x98, 0xe8,
	0xa1, 0xab, 0x54, 0xb9, 0x17, 0xba, 0x20, 0x67, 0x24, 0xf7, 0xcc, 0xd7, 0xc5, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xf3, 0xaf, 0x17, 0xa5, 0xe4, 0x01, 0x00, 0x00,
}
